### ISSUE TITLE
Bot crashes when cannot post

### ISSUE THREAD

**Issue by wbratz** [wbratz/prolice-slack-bot#10]
Currently the bot panics and quits when it cannot post, or ping. Instead I'd like to not exit or crash and keep retrying the connection until it can be reestablished. That way we don't lose what is in memory by restarting the bot.

**Comment by wbratz** [comment]
Error message on exit
`panic: send on closed channel

goroutine 373 [running]:
github.com/slack-go/slack/socketmode.(*Client).receiveMessagesInto(0xc0001545a0, {0xc9baf8, 0xc000028b40}, 0x0?, 0xc00001b1a0)
        C:/Users/BBratz/go/pkg/mod/github.com/slack-go/slack@v0.11.4/socketmode/socket_mode_managed_conn.go:484 +0x3df
github.com/slack-go/slack/socketmode.(*Client).runMessageReceiver(...)
        C:/Users/BBratz/go/pkg/mod/github.com/slack-go/slack@v0.11.4/socketmode/socket_mode_managed_conn.go:363
github.com/slack-go/slack/socketmode.(*Client).run.func4()
        C:/Users/BBratz/go/pkg/mod/github.com/slack-go/slack@v0.11.4/socketmode/socket_mode_managed_conn.go:133 +0xab
created by github.com/slack-go/slack/socketmode.(*Client).run
        C:/Users/BBratz/go/pkg/mod/github.com/slack-go/slack@v0.11.4/socketmode/socket_mode_managed_conn.go:128 +0x73e
exit status 2`
